# Generated by Django 5.1.1 on 2025-02-21 16:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_delete_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='status',
            field=models.CharField(choices=[('borrowed', 'borrowed'), ('returned', 'returned')], default='borrowed', max_length=100),
        ),
        migrations.AddField(
            model_name='borrow',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
