# Generated by Django 5.1.1 on 2025-02-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_borrow_status_borrow_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
